filter:
    excluded_paths: [tests/*]

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

build:
    # https://prinsfrank.nl/2022/02/04/Configuring-PHP8.1-on-scrutinizer
    image: default-bionic
    environment:
        php:
            version: 8.4.4
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            environment:
                variables:
                    XDEBUG_MODE: coverage
            tests:
                override:
                    - command: composer test-coverage
                      coverage:
                          file: build/logs/coverage.xml
                          format: clover

