#!/usr/bin/env php
<?php declare(strict_types = 1);

use Dominikb\ComposerLicenseChecker\CheckCommand;
use Dominikb\ComposerLicenseChecker\ConstraintViolationDetector;
use Dominikb\ComposerLicenseChecker\DependencyLoader;
use Dominikb\ComposerLicenseChecker\LicenseLookup;
use Dominikb\ComposerLicenseChecker\ReportCommand;
use GuzzleHttp\Client;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputDefinition;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\ConsoleOutput;

require_once __DIR__ . '/vendor/autoload.php';

$output = new ConsoleOutput();

$httpClient = new Client;

$licenceLookUp = new LicenseLookup($httpClient);

$checkCommand = new CheckCommand;
$checkCommand->setLicenseLookup($licenceLookUp);
$checkCommand->setLicenseConstraintHandler(new ConstraintViolationDetector);
$checkCommand->setDependencyLoader(new DependencyLoader);

$reportCommand = new ReportCommand;
$reportCommand->setLicenseLookup($licenceLookUp);
$reportCommand->setDependencyLoader(new DependencyLoader);

$application = new Application('composer-license-checker', '1.0.0');

$application->addCommands([$checkCommand, $reportCommand]);

$application->run();
